USE restaurantdatabase;

INSERT INTO restaurant_orders (customer_name, dish_name, order_day, price) VALUES
('David Wilson', 'Caprese Salad', 'Wednesday', 9.99),
('Emma Davis', 'Chicken Alfredo', 'Wednesday', 14.99),
('Michael Johnson', 'Pepperoni Pizza', 'Thursday', 12.99),
('Olivia Miller', 'Chocolate Cake', 'Thursday', 6.99),
('William Smith', 'Spaghetti Bolognese', 'Friday', 12.99),
('Sophia Davis', 'Margherita Pizza', 'Friday', 10.99),
('Daniel Brown', 'Caesar Salad', 'Saturday', 8.99),
('Emily White', 'Chicken Alfredo', 'Saturday', 14.99),
('Liam Wilson', 'Tiramisu', 'Sunday', 7.99),
('Ava Taylor', 'Spaghetti Bolognese', 'Sunday', 12.99),
('Ethan Miller', 'Pepperoni Pizza', 'Monday', 12.99),
('Mia Davis', 'Chicken Alfredo', 'Monday', 14.99),
('James Johnson', 'Margherita Pizza', 'Tuesday', 10.99),
('Ava Smith', 'Caprese Salad', 'Tuesday', 9.99),
('Noah Wilson', 'Chocolate Cake', 'Wednesday', 6.99),
('Sophia Martinez', 'Spaghetti Bolognese', 'Wednesday', 12.99),
('James Brown', 'Caesar Salad', 'Thursday', 8.99),
('Olivia Taylor', 'Chicken Alfredo', 'Thursday', 14.99),
('William Anderson', 'Tiramisu', 'Friday', 7.99),
('Amelia Thomas', 'Pepperoni Pizza', 'Friday', 12.99),
('Ethan Jackson', 'Margherita Pizza', 'Saturday', 10.99),
('Ava White', 'Chocolate Cake', 'Saturday', 6.99),
('Alexander Harris', 'Caprese Salad', 'Sunday', 9.99),
('Mia Clark', 'Chicken Alfredo', 'Sunday', 14.99),
('Benjamin Young', 'Spaghetti Bolognese', 'Monday', 12.99),
('Charlotte Lewis', 'Caesar Salad', 'Monday', 8.99),
('Daniel Lee', 'Margherita Pizza', 'Tuesday', 10.99),
('Harper Walker', 'Tiramisu', 'Tuesday', 7.99),
('Henry Hall', 'Pepperoni Pizza', 'Wednesday', 12.99),
('Ella Hill', 'Caprese Salad', 'Wednesday', 9.99),
('Jacob Green', 'Chocolate Cake', 'Thursday', 6.99),
('Liam Adams', 'Spaghetti Bolognese', 'Thursday', 12.99),
('Avery Baker', 'Caesar Salad', 'Friday', 8.99),
('Sofia Nelson', 'Chicken Alfredo', 'Friday', 14.99),
('Logan King', 'Tiramisu', 'Saturday', 7.99),
('Evelyn Scott', 'Pepperoni Pizza', 'Saturday', 12.99),
('Lucas Rivera', 'Margherita Pizza', 'Sunday', 10.99),
('Madison Mitchell', 'Caprese Salad', 'Sunday', 9.99),
('Jackson Perez', 'Chocolate Cake', 'Monday', 6.99),
('Victoria Carter', 'Spaghetti Bolognese', 'Monday', 12.99),
('Sebastian Roberts', 'Caesar Salad', 'Tuesday', 8.99),
('Penelope Sanchez', 'Chicken Alfredo', 'Tuesday', 14.99),
('Levi Ross', 'Tiramisu', 'Wednesday', 7.99),
('Zoey Evans', 'Pepperoni Pizza', 'Wednesday', 12.99),
('Gabriel Morris', 'Margherita Pizza', 'Thursday', 10.99),
('Lily Garcia', 'Caprese Salad', 'Thursday', 9.99),
('Isaac Butler', 'Chocolate Cake', 'Friday', 6.99),
('Grace Cooper', 'Spaghetti Bolognese', 'Friday', 12.99),
('Anthony Murphy', 'Caesar Salad', 'Saturday', 8.99),
('Julian Torres', 'Chicken Alfredo', 'Saturday', 14.99),
('Aria Brooks', 'Tiramisu', 'Sunday', 7.99),
('Lincoln Morgan', 'Pepperoni Pizza', 'Sunday', 12.99),
('Elizabeth Reed', 'Margherita Pizza', 'Monday', 10.99),
('Christopher Wood', 'Caprese Salad', 'Monday', 9.99),
('Addison Bailey', 'Chocolate Cake', 'Tuesday', 6.99),
('Ryan Flores', 'Spaghetti Bolognese', 'Tuesday', 12.99),
('Elena Wright', 'Caesar Salad', 'Wednesday', 8.99),
('David Collins', 'Chicken Alfredo', 'Wednesday', 14.99),
('Nora Price', 'Tiramisu', 'Thursday', 7.99),
('Eliana Stewart', 'Pepperoni Pizza', 'Thursday', 12.99),
('Christian Sanchez', 'Margherita Pizza', 'Friday', 10.99),
('Eva Martinez', 'Caprese Salad', 'Friday', 9.99),
('Landon Turner', 'Chocolate Cake', 'Saturday', 6.99),
('Samantha Reed', 'Spaghetti Bolognese', 'Saturday', 12.99),
('Leo Collins', 'Caesar Salad', 'Sunday', 8.99),
('Aubrey Turner', 'Chicken Alfredo', 'Sunday', 14.99),
('Oscar Hayes', 'Tiramisu', 'Monday', 7.99),
('Maya Powell', 'Pepperoni Pizza', 'Monday', 12.99),
('Caleb Rodriguez', 'Margherita Pizza', 'Tuesday', 10.99),
('Eleanor Scott', 'Caprese Salad', 'Tuesday', 9.99),
('Dylan Nelson', 'Chocolate Cake', 'Wednesday', 6.99),
('Hailey Parker', 'Spaghetti Bolognese', 'Wednesday', 12.99),
('Eli Bennett', 'Caesar Salad', 'Thursday', 8.99),
('Zoe Coleman', 'Chicken Alfredo', 'Thursday', 14.99),
('Maxwell Price', 'Tiramisu', 'Friday', 7.99),
('Madeline Ward', 'Pepperoni Pizza', 'Friday', 12.99),
('Xavier Hughes', 'Margherita Pizza', 'Saturday', 10.99),
('Isabelle Bell', 'Caprese Salad', 'Saturday', 9.99),
('Brayden Brooks', 'Chocolate Cake', 'Sunday', 6.99),
('Skylar Turner', 'Spaghetti Bolognese', 'Sunday', 12.99),
('Lucy Foster', 'Caesar Salad', 'Monday', 8.99),
('Owen Hunt', 'Chicken Alfredo', 'Monday', 14.99),
('Gemma Foster', 'Tiramisu', 'Tuesday', 7.99),
('Mason Turner', 'Pepperoni Pizza', 'Tuesday', 12.99),
('Clara Hayes', 'Margherita Pizza', 'Wednesday', 10.99),
('Henry Parker', 'Caprese Salad', 'Wednesday', 9.99),
('Nova Nelson', 'Chocolate Cake', 'Thursday', 6.99),
('Ezra Bennett', 'Spaghetti Bolognese', 'Thursday', 12.99),
('Stella Ward', 'Caesar Salad', 'Friday', 8.99),
('Silas Hughes', 'Chicken Alfredo', 'Friday', 14.99),
('Aurora Bell', 'Tiramisu', 'Saturday', 7.99),
('Ezekiel Brooks', 'Pepperoni Pizza', 'Saturday', 12.99),
('Luna Coleman', 'Margherita Pizza', 'Sunday', 10.99),
('Kai Bell', 'Caprese Salad', 'Sunday', 9.99),
('Hazel Foster', 'Chocolate Cake', 'Monday', 6.99),
('Miles Hayes', 'Spaghetti Bolognese', 'Monday', 12.99),
('Eva Turner', 'Caesar Salad', 'Tuesday', 8.99),
('James Ward', 'Chicken Alfredo', 'Tuesday', 14.99),
('Ella Foster', 'Tiramisu', 'Wednesday', 7.99),
('Jackson Turner', 'Pepperoni Pizza', 'Wednesday', 12.99),
('Avery Hayes', 'Margherita Pizza', 'Thursday', 10.99),
('Emma Coleman', 'Caprese Salad', 'Thursday', 9.99),
('Oscar Bennett', 'Chocolate Cake', 'Friday', 6.99),
('Lily Ward', 'Spaghetti Bolognese', 'Friday', 12.99),
('Logan Hughes', 'Caesar Salad', 'Saturday', 8.99),
('Sophie Foster', 'Chicken Alfredo', 'Saturday', 14.99),
('Oliver Bell', 'Tiramisu', 'Sunday', 7.99),
('Violet Brooks', 'Pepperoni Pizza', 'Sunday', 12.99),
('Leo Bennett', 'Margherita Pizza', 'Monday', 10.99),
('Aria Hayes', 'Caprese Salad', 'Monday', 9.99),
('Elijah Turner', 'Chocolate Cake', 'Tuesday', 6.99),
('Lucy Ward', 'Spaghetti Bolognese', 'Tuesday', 12.99),
('Mila Hughes', 'Caesar Salad', 'Wednesday', 8.99),
('Zachary Foster', 'Chicken Alfredo', 'Wednesday', 14.99),
('Ava Bell', 'Tiramisu', 'Thursday', 7.99),
('Landon Turner', 'Pepperoni Pizza', 'Thursday', 12.99),
('Emma Hayes', 'Margherita Pizza', 'Friday', 10.99),
('Mason Coleman', 'Caprese Salad', 'Friday', 9.99),
('Eva Bennett', 'Chocolate Cake', 'Saturday', 6.99),
('Jackson Turner', 'Spaghetti Bolognese', 'Saturday', 12.99),
('Ella Hughes', 'Caesar Salad', 'Sunday', 8.99),
('Owen Foster', 'Chicken Alfredo', 'Sunday', 14.99),
('Sophia Bell', 'Tiramisu', 'Monday', 7.99),
('Liam Hayes', 'Pepperoni Pizza', 'Monday', 12.99),
('Chloe Turner', 'Margherita Pizza', 'Tuesday', 10.99),
('Ethan Hayes', 'Caprese Salad', 'Tuesday', 9.99),
('Avery Coleman', 'Chocolate Cake', 'Wednesday', 6.99),
('Aria Ward', 'Spaghetti Bolognese', 'Wednesday', 12.99),
('Oscar Hughes', 'Caesar Salad', 'Thursday', 8.99),
('Ella Turner', 'Chicken Alfredo', 'Thursday', 14.99),
('Leo Bell', 'Tiramisu', 'Friday', 7.99),
('Aria Hayes', 'Pepperoni Pizza', 'Friday', 12.99),
('Emma Coleman', 'Margherita Pizza', 'Saturday', 10.99),
('Mason Turner', 'Caprese Salad', 'Saturday', 9.99),
('Eva Bennett', 'Chocolate Cake', 'Sunday', 6.99),
('Jackson Turner', 'Spaghetti Bolognese', 'Sunday', 12.99);